//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Competition
    {
        public int COMPETITION_ID { get; set; }
        public Nullable<System.DateTime> DATE { get; set; }
        public Nullable<int> OVERALL_PLACES { get; set; }
        public Nullable<int> CLASS_PLACES { get; set; }
        public Nullable<int> NUMBER_OF_CLASSES { get; set; }
        public Nullable<int> CLASS_ONE_MIN { get; set; }
        public Nullable<int> CLASS_ONE_MAX { get; set; }
        public Nullable<int> CLASS_TWO_MIN { get; set; }
        public Nullable<int> CLASS_TWO_MAX { get; set; }
        public Nullable<int> CLASS_THREE_MIN { get; set; }
        public Nullable<int> CLASS_THREE_MAX { get; set; }
        public Nullable<bool> FRONT_NINE { get; set; }
        public Nullable<bool> BACK_NINE { get; set; }
        public Nullable<bool> NEAREST_PIN { get; set; }
        public Nullable<bool> LONGEST_DRIVE { get; set; }
        public Nullable<int> COURSE_ID { get; set; }
    
        public virtual Course TBL_COURSE { get; set; }
    }
}
