//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Player
    {
        public int PLAYER_ID { get; set; }
        public string FIRST_NAME { get; set; }
        public string LAST_NAME { get; set; }
        public string FULLNAME { get; set; }
        public Nullable<int> HANDICAP { get; set; }
        public Nullable<int> ADJUST { get; set; }
        public string ADDRESS { get; set; }
        public string PHONE { get; set; }
        public string EMAIL { get; set; }
        public string CLUB { get; set; }
        public Nullable<System.DateTime> JOINDATE { get; set; }
        public string IMAGE { get; set; }
    }
}
